// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/auth/auth.go

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	reflect "reflect"

	whatsapp "github.com/Rhymen/go-whatsapp"
	gomock "github.com/golang/mock/gomock"
	session "github.com/r-erema/wapi/internal/model/session"
)

// MockAuthorizer is a mock of Authorizer interface
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// Login mocks base method
func (m *MockAuthorizer) Login(sessionId string) (*whatsapp.Conn, *session.WapiSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", sessionId)
	ret0, _ := ret[0].(*whatsapp.Conn)
	ret1, _ := ret[1].(*session.WapiSession)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login
func (mr *MockAuthorizerMockRecorder) Login(sessionId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthorizer)(nil).Login), sessionId)
}
