// Code generated by MockGen. DO NOT EDIT.
// Source: /home/roman.erema/go/src/wapi/src/Service/MessageListener/Interface.go

// Package mock_MessageListener is a generated GoMock package.
package mock_MessageListener

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	sync "sync"
)

// MockInterface is a mock of Interface interface
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// ListenForSession mocks base method
func (m *MockInterface) ListenForSession(sessionId string, wg *sync.WaitGroup) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListenForSession", sessionId, wg)
}

// ListenForSession indicates an expected call of ListenForSession
func (mr *MockInterfaceMockRecorder) ListenForSession(sessionId, wg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenForSession", reflect.TypeOf((*MockInterface)(nil).ListenForSession), sessionId, wg)
}
